### ISSUE TITLE
Uploading transactions crashes the app

### ISSUE THREAD

**Issue by tu-tran** [andersnylund/simple-budgeting#35]
Go to Import -> Clear
Then go to Import page again, select Danske bank, select the sample Danske bank transactions. --> Crash

**Comment by andersnylund** [comment]
Hmm, I am on master branch and it is working fine for me 🤔. Could you show the console errors if there are any

**Comment by tu-tran** [comment]
oops sorry, I think I made a typo in description. I have "not" selected Danske bank before uploading t he file, which caused the crash (so apparently no default bank was selected in fresh clear state)

**Comment by tu-tran** [comment]
This is not reproducabl anymore with the latest code
